### ISSUE TITLE
Editor slowing dramatically for large raml (850+) lines on Chrome 

### ISSUE THREAD

**Issue by ricston-git** [mulesoft/api-designer#186]
RAML files (850 lines +) that the editor seems to slow to a crawl in Chrome
on Windows. Unfortunately I cannot share the raml file. 

r

**Comment by sichvoge** [comment]
@ricston-git: did you find a solution for this? i am still convinced that the guys will find a solution as this is related to different parts starting with the parser.

do you get the same behaviour when splitting the RAML file into parts?

**Comment by sichvoge** [comment]
Closing that as it is related to #210
