### ISSUE TITLE
Blank screen on the browser

### ISSUE THREAD

**Issue by MCalder423** [mulesoft/api-designer#193]
I had downloaded the designer a couple of months ago, and had it set up and running fine.  I wanted to refresh the code to take advantage of the new shiny that you guys are doing, but the latest version that I pulled just brings up the browser with a blank screen.  There's content behind it (lots of javascript tags) but nothing I can actually see.  any thoughts?

**Comment by sichvoge** [comment]
tried the installation guide and it works. I'll close this issue - if anyone experience that again, it can be opened again.
