### ISSUE TITLE
Getting started docs

### ISSUE THREAD

**Issue by sinukus** [mulesoft/api-designer#197]
Took me a while to get things going because of some missing and misleading steps in your docs at
https://github.com/mulesoft/api-designer/

Missing step:
install grunt protractor
>npm install grunt-protractor-runner

erroneous step:
Install webdriver required to run localScenario task

node_modules/grunt-protractor-runner/node_modules/protractor/bin/webdriver-manager update

Should be:
Install webdriver required to run localScenario task

node node_modules/grunt-protractor-runner/node_modules/protractor/bin/webdriver-manager update

I had no idea that the last step here needed to be run by node.

**Comment by jxc876** [comment]
I had the same issue on Windows 7, the instructions on the front page didn't work, I I needed to append "node" before the command ran:

node_modules\grunt-protractor-runner\node_modules\protractor\bin\webdriver-manager update

**Comment by sichvoge** [comment]
fixed in latest merge!
