### ISSUE TITLE
Not deterministic response merge

### ISSUE THREAD

**Issue by maryoush** [mulesoft/api-designer#203]
Imagine we have a raml modelling some api 

<pre>
#%RAML 0.8
---

title: Configuration Service
baseUri: http://configuration.cf.com/
version: v1
mediaType: application/json

traits:
  - !include http://api.cf.com/patterns/v1/trait-paged.yaml
  - !include http://api.cf.com/patterns/v1/trait-limited.yaml
 
/configurations:
  is: [paged,limited]
  displayName: Configuration properties
  description: Manages configuration properties
  get:
    description: Gets all configuration properties
    responses:
      200:
        description: Property retrieved
      500:
        description: Internal server error

</pre>

The both traits define the response code 400 differently - description wise.
I would expect that api designer some how combines those descriptions so the both 'natures' are visible to api client.

Currently it uses the first which is declared for the given method ...

**Comment by sichvoge** [comment]
more like a spec issue
