### ISSUE TITLE
API designer CORS(?) issue

### ISSUE THREAD

**Issue by maryoush** [mulesoft/api-designer#204]
Hi,
We have strange inconvenience regarding the including externals within RAML across domains.

There is sample RAML

<pre>
#%RAML 0.8
title: hybris Products API
baseUri: http://localhost:8080/
version: v1
mediaType:  application/json

schemas:
  - error : !include http://localhost:8080/patterns/v1/schema-error-message.json

/products:
  get:
    description: Gets all products
    responses:  
     500 :
        body:
         schema : error

</pre>

The schema content.

<pre>
{
  "$schema":"http://json-schema.org/draft-04/schema#",
  "title":"error",
  "type":"object",
  "properties":
  {
    "status":
    {
      "type":"integer",
      "minimum":"100",
      "maximum":"599"
    },
    "type":
    {
      "type":"string",
      "pattern":"[a-z]+[[a-z]_]*[a-z]+"
    },
    "message":
    {
      "type":"string"
    },
    "moreInfo":
    {
      "type":"string",
      "format":"uri"
    },
    "details":
    {
      "type":"array",
      "items":
      {
        "$schema":"http://json-schema.org/draft-04/schema#",
        "title":"errorDetail",
        "type":"object",
        "properties":
        {
          "field":
          {
            "type":"string"
          },
          "type":
          {
            "type":"string",
            "pattern":"[a-z]+[[a-z]_]*[a-z]+"
          },
          "message":
          {
            "type":"string"
          },
          "moreInfo":
          {
            "type":"string",
            "format":"uri"
          }
        },
        "required":["type"]
      }
    }
  },
  "required":["status" , "type" ]
}
</pre>

We have patterns deployed in container where the CORS is enabled(this CORS enablement works for other web apps)  :

<pre>

&lt;filter&gt;
        &lt;filter-name&gt;CORS&lt;/filter-name&gt;
        &lt;filter-class&gt;com.thetransactioncompany.cors.CORSFilter&lt;/filter-class&gt;
        &lt;init-param&gt;
            &lt;param-name&gt;cors.maxAge&lt;/param-name&gt;
            &lt;param-value&gt;1&lt;/param-value&gt;
        &lt;/init-param&gt;
    &lt;/filter&gt;
    &lt;filter-mapping&gt;
        &lt;filter-name&gt;CORS&lt;/filter-name&gt;
        &lt;url-pattern&gt;/*&lt;/url-pattern&gt;
    &lt;/filter-mapping&gt;

 </pre>
 
 The similar CORS enablement is add in the api-designer web app.
 
 We got a strange message issue see snapshot.
<ul>
<li>
  Surprisingly it does not occur for any other content served remotely like e.g. yaml files 
containing traits, resource types.
</li>
<li>
  What is more - if i download the file and reference it locally it works as a charm 
</li>
</ul> 
<pre>
#%RAML 0.8
title: hybris Products API
baseUri: http://localhost:8080/
version: v1
mediaType:  application/json

#schemas:
#  - error : !include http://localhost:8080/patterns/v1/schema-error-message.json
traits:
  - !include http://localhost:8080/patterns/v1/trait-paged.yaml
/products:
  get:
    description: Gets all products
    responses:  
     500 :
        body:
         schema : error

</pre>

The issue occurs on the ( OS X Mavericks 10.9 )
- Chrome version 35.0.1916.114 (normal , incognito window)
- FireFox 25.0.1

![screen shot 2014-06-13 at 09 58 35](https://cloud.githubusercontent.com/assets/3878520/3268020/52303a76-f2d6-11e3-8e18-eab87bd968ad.png)

**Comment by carowright** [comment]
Hi @maryoush! 
Sorry for the late response. I am closing this issue as this error is no longer in the latest version (v0.4.10).
