### ISSUE TITLE
Font locking breaks when * appears in a resource's URI

### ISSUE THREAD

**Issue by dwcramer** [mulesoft/api-designer#219]
I have a resource whose URI is something like:
/api/v1/widget/*/tags/{tag}
When I add it to my document in the api-designer, everything up to and including the \* is white while things after the */ are red, as is usual for URI templates. However \* is a legal character in a paths. See:
http://tools.ietf.org/html/rfc3986#section-3.3
I notice a few other "subdelims" confuse the api-designer as well: ~, $, =, etc. 
I don't know if these characters will end up confusing other tools in the RAML tool chain, but the api-designer gives the impression that paths containing them are not legal.

**Comment by sichvoge** [comment]
@dmartinezg this is still open and not working. is it a problem coming from the parser?

**Comment by sichvoge** [comment]
just realised the parsing is not the problem, it's really just a font thing. i'll try to dig dive into that

**Comment by sichvoge** [comment]
Its still an issue with the syntax highlighter.

**Comment by nmarinel01** [comment]
Hi dwcramer,
Cannot reproduce that behavior using latest Api Designer version.
Please, will you verify again and reopen if necessary ?
Thanks
