### ISSUE TITLE
'Try it' needs a 'Use example values' checkbox

### ISSUE THREAD

**Issue by scordatura** [mulesoft/api-designer#222]
In the **API Reference**, we have some (body) **Headers** for some methods. In the **Try it** panel, the **Headers** are text fields with example values in gray.

To actually use the example values (which we do, a lot) we must type or copy/paste over them. Our testers find this awkward and onerous. If we had a **Use example values** checkbox we could save a hell of a lot of clicks or keystrokes.

**Comment by sichvoge** [comment]
Available with the new API Console v2.0
