### ISSUE TITLE
Reversing order of page titles would make them more useful

### ISSUE THREAD

**Issue by scordatura** [mulesoft/api-designer#223]
If I have **API Designer** on one tab, **Portal** on another, **API administration** on another, etc, all I see on the tabs is **Anypoint** for the pages other than the one in front. I already know they're all Anypoint by virtue of the icon that appears before the word, which is long enough to take up all the visible space in the tab.

This is not very useful. In Chrome, I need to use the Window menu to see the full titles of these pages, which have multiple parts, for example:

     Anypoint Platform for APIs / API Administration / <API_name> / Designer 

Why not reverse the order?

     Designer / <API_name> / API Administration / Anypoint Platform for APIs

Then I would have the good user experience of seeing tabs for **Designer**, **API Administration**, **API Reference**, etc, and not have to bother with the Window menu to figure out where a particular tab is.

**Comment by sichvoge** [comment]
This issue is not related to the api-designer instance, but more to MuleSoft's Anypoint Platform product. Therefore, I am closing it.
