### ISSUE TITLE
Request/response schema/example 

### ISSUE THREAD

**Issue by twolff-iow** [mulesoft/api-designer#236]
Hi,

currently, RAML defines both an example and a schema for a request and response. While I understand that the example is (and should be) just an XML or a JSON which is displayed by the designer/console as code, are there any plans to display the schema a bit differently? AFAIU a schema contains the information about the fields, its data types and it's constraints (max/min values, enum values, etc.). It would be very nice, if the schema would be displayed as kind of a table with the field name, the field type, whether it is required or not, the description, etc. This is was I frequently use when coding against an API to lookup the fields and its allowed values.

Tobias.

**Comment by sichvoge** [comment]
@usarid do you know where we are w/ that? it's more related to the api console, therefore i might create a new issue there as a proposal for a new feature. It's pretty cool, therefore I would love to have that in.

**Comment by usarid** [comment]
Nothing to say from my side at this point, other than that I agree that schema in general could benefit from a lot of UX love

**Comment by sichvoge** [comment]
@dmartinezg, @alejandroschenzle & @blakeembrey what do you guys think of the docson project? shouldn't be to hard to integrate :P

**Comment by robertlevy** [comment]
docson looks like it makes a lot of assumptions about how to load files.  would be great to see this type of UX integrated but it probably needs a refactoring first

Date: Wed, 17 Jun 2015 11:40:59 -0700

**Comment by sichvoge** [comment]
@robertlevy refactoring the designer or docson?

**Comment by robertlevy** [comment]
Refactoring docson so it can pull from an abstract storage system (like the designer already does)

**Comment by sichvoge** [comment]
Do you think it makes sense to contact him, or do you think it make sense to fork and work on that?

**Comment by sichvoge** [comment]
This is related to https://github.com/mulesoft/api-console/issues/82. Closing it here since that is more related to the console.
