### ISSUE TITLE
NPM package

### ISSUE THREAD

**Issue by robertlevy** [mulesoft/api-designer#247]
Would be great to have an NPM package for this project containing just the build output.  Pulling the whole source tree into my project is overkill.

**Comment by jmagnusson** [comment]
Agreed. This would be a great addition.

**Comment by sichvoge** [comment]
@blakeembrey @dmartinezg @alejandroschenzle @usarid i think that would be great! what are your thoughts?

**Comment by blakeembrey** [comment]
:+1:

**Comment by sichvoge** [comment]
As I am not familiar with the process - @blakeembrey would you be so kind to do that or we can have a quick chat and I am doing it by myself. :)
