### ISSUE TITLE
Resource name is invalid: illegal character

### ISSUE THREAD

**Issue by sichvoge** [mulesoft/api-designer#275]
The API Designer (version something on 2015-01-01) reports

`Resource name is invalid: illegal character`

when there is a hyphen in a uriParameter, e.g.

```
/bug{a-b}:
  uriParameters:
    a-b:
      enum: [ a-b ]
```

Quick fix: use underscores instead of hyphens.

Issues:

Hyphen is a legal YAML word character.
Hyphens are allowed in resource names.
Hyphen causes no problems in a uriParameter name.
The hyphen is in the template expression, not in the resource name.
The problem is that RFC 6570 does not allow hyphens in variable names.
Suggestions:

Change the error message to something like 
`Invalid uriParameter name: illegal character '-'`
Check the validity of uriParameter and baseUriParameter names.

Source: http://forums.raml.org/t/resource-name-is-invalid-illegal-character/614/2

**Comment by dmartinezg** [comment]
Can you please open this bug in the https://github.com/raml-org/raml-js-parser/issues repo?

**Comment by sichvoge** [comment]
closing this as it is related to the parser and not the designer.
