### ISSUE TITLE
custom securityScheme not behaving like a trait

### ISSUE THREAD

**Issue by hanoii** [mulesoft/api-designer#288]
not sure if I understood the spec wrong, but I first defined a secured trait, then I realized I could define it is as a securityscheme, it's a custom one using JWT, however, by doing that, I don't see the responses and headers defined in the describedBy property. I thought that it should behave exactly like a trait.

Am I doing something wrong. This didn't work on the api designer, nor on the raml2html project.

**Comment by ex-nerd** [comment]
+1 to this.  I know that raml2html has its own issues (on the todo) about displaying the securityscheme info, but it at least shows a "secured by <scheme>" even if it doesn't show the details.  Would love to see something similar in api-designer.

**Comment by sichvoge** [comment]
It's showing up in the api-console now. Therefore, closing it.
