### ISSUE TITLE
Pressing ctrl(or cmd)+d with a whole line selected deletes the next line

### ISSUE THREAD

**Issue by vromero** [mulesoft/api-designer#292]
Open designer and a RAML
Triple click in a line to select the whole line, press ctrl(or cmd)+d to delete the line. 
The line+1 will get deleter rather than the current one.

**Comment by dmartinezg** [comment]
Interestingly enough, `control+d` in a mac does the right thing.

**Comment by sichvoge** [comment]
This is still an issue!

**Comment by nmarinel01** [comment]
Not reproducible any more.
