### ISSUE TITLE
Mocking service base URI forgotten when re-opening RAML after a few weeks

### ISSUE THREAD

**Issue by melissavdh** [mulesoft/api-designer#296]
I opened a RAML file after leaving it untouched for a few weeks.  The toggle for the Mocking Service was ON, but the base URI in the RAML was my real one as opposed to one for the Mocking Service.  It seems as though the state of the Mocking Service toggle was remembered from the last time I used it, but the base URI had been lost.  I had to turn it off and then on again in order for it to work as expected.

**Comment by jcenturion** [comment]
Hi @melissavdh, thanks for feedback. We'll take a look.
