### ISSUE TITLE
 Nested item's schema is never shown

### ISSUE THREAD

**Issue by vsertti** [mulesoft/api-designer#298]
$ref doesn't seem to be parsed by API Designer or raml2html, so the nested item's schema is never shown.
I would like to use nested schema. It does not work.  
 http://stackoverflow.com/questions/27055536/raml-nested-schemas

"type": "object",
  "name": "SampleEnumerationListDto",
  "properties": {
    "SampleEvents": {
      "type": "array",
      "description": "Array of sample events",
      "items": {"$ref": "SampleEventDTO" },  // I would like to see DTO here
      "required": true
      },

**Comment by robertlevy** [comment]
+1

**Comment by dmartinezg** [comment]
This is not entirely a Designer issue, I would argue that this is a limitation of RAML itself.

Can you open an issue in https://github.com/raml-org/raml-spec/issues ?

**Comment by vsertti** [comment]
Hi !
I opened an issue.
Nested item's schema is never shown #149
Rgs, Veli

Lähettäjä: Damian Martinez Gelabert [mailto:notifications@github.com]
Lähetetty: 28. huhtikuuta 2015 14:58
Vastaanottaja: mulesoft/api-designer
Kopio: Sertti Veli
Aihe: Re: [api-designer] Nested item's schema is never shown (#298)


This is not entirely a Designer issue, I would argue that this is a limitation of RAML itself.

Can you open an issue in https://github.com/raml-org/raml-spec/issues ?

**Comment by sichvoge** [comment]
I think that is a limitation on the parser!

**Comment by sichvoge** [comment]
closing this issue as the root problem is the current implementation of the parser as discussed in raml-org/raml-spec#149. A new implementation is currently in development and shall fix the problem.
