### ISSUE TITLE
Extending Help Menu

### ISSUE THREAD

**Issue by sichvoge** [mulesoft/api-designer#305]
I would like to have more menu items/options inside the API Designer to point people where they can find the specification or the repository to file issues. Right now, I think of the following items:

* RAML Spec
* raml.org website
* Report a Bug
* Getting Started with RAML

**Comment by sichvoge** [comment]
Just to give an update - this is what I have right now.

![image](https://cloud.githubusercontent.com/assets/498114/8243321/01072d7e-160e-11e5-921f-296312a9f8cb.png)

Can someone point me to the CSS related to the submenu?

**Comment by sichvoge** [comment]
Update: Changed "Getting Started with RAML" to "RAML Tutorial"

**Comment by dmartinezg** [comment]
Do we have a standard width for menus? if we do, let's make sure that menu lines do not wrap, `RAML tutorial` seems shorter.

The alliteration of the word RAML everywhere can probably be avoided.

**Comment by sichvoge** [comment]
I am looking for the CSS w/o success so far.

**Comment by sichvoge** [comment]
Done with PR #319
