### ISSUE TITLE
Running into issue with APIDesigner on linux

### ISSUE THREAD

**Issue by rajkumar1979** [mulesoft/api-designer#306]
We are trying to test API Designer on a linux machine and by default the API Designer runs on localhost, I tried changing that parameter in the GruntFilejs but it always picks up the default locahost, how can we change this?

Thanks

Raj.

**Comment by dmartinezg** [comment]
Hi @rajkumar1979, that grunt recipe is just for local development of API designer, I strongly recommend that you host API designer in your own application/web server instead of the grunt task.

**Comment by rajkumar1979** [comment]
Could you please share on how you can deploy this and run in tomcat .

**Comment by rajkumar1979** [comment]
Hi ,

I would appreciate if you can share some details on what are the best practices of hosting the API Designer in a tomcat server and why we should not rely on the grunt recipe?

**Comment by dmartinezg** [comment]
@rajkumar1979, I do not know how to do this in tomcat.

You would need to build an HTML like this https://github.com/mulesoft/api-designer/blob/master/app/index.html one, and host it within tomcat.
