### ISSUE TITLE
Improving the menu UX

### ISSUE THREAD

**Issue by sichvoge** [mulesoft/api-designer#317]
Currently, we have a very minimalistic menu which I would like to improve to make it more visual attractive. Additionally, I want to extend it and modify the existing menu items. 

At the moment I am thinking of having the following menus based on existing standard IDEs (and I am open for any suggestions):

Main: Project
Sub: New File, New Folder, Save, Save All, Import, Export 

Main: Generate
Sub: Documentation (Sub: HTML, etc.)
Sub: Client SDK (Sub: Javascript, etc.)
Sub: Server SDK (Sub: ...)
Sub: <<maybe more>>

Main: Help
Sub: RAML Specification
Sub: raml.org Website
Sub: Report a Bug
Sub: Getting Started Guide

This enhancement is going one step further than issue #305

**Comment by robjens** [comment]
How about a way to actually *open* a file? Or am I missing something crucial. All to do now is to copy paste content, since `api-designer <filename>` doesn't work as e.g. sublime or atom.

**Comment by sichvoge** [comment]
You're right! Today, we don't support opening files via command lines as this version does not provide storing files on the filesystem. It still relies on the browser cache and therefore needs to be imported. Speaking of importing files, you could potentially zip your files and use the `Import` menu to get your RAML inside the designer w/o having to copy&paste. 

We potentially provide a version where you will be able to store your files locally -> if we will get that, we could potentially add support for command line commands.

**Comment by sichvoge** [comment]
We think about the current menu structure:

- Project
  - New File
    - RAML 1.0
      - API Spec
      - (all fragments)
    - RAML 0.8 API Spec
  - New Folder
  - Save
  - Save All
  - Import
  - Export
    - Project Zip
    - Swagger 2.0 JSON
    - Swagger 2.0 YAML
- View
  - Toggle Background Color (CTRL + SHIFT + T)
- Help
  - RAML Specification
  - raml.org Website
  - Report Bug
  - Getting Started Guide
  - About

Every fragment should be followed by a respective modal with the following text: description, example, link to the spec; as well as an input field for the name. I will soon add an example to this issue.

We should also have proper padding (top and bottom).

**Comment by sichvoge** [comment]
"New File" content should also be inside the context menu inside the directory view.

![image](https://cloud.githubusercontent.com/assets/498114/19050585/23ca3fe6-89a7-11e6-936f-dfb53604660d.png)

**Comment by sichvoge** [comment]
@nmarinel01 this can be closed right?

**Comment by nmarinel01** [comment]
Yes ! You're right. Closing. Thanks
