### ISSUE TITLE
Return to the same vertical scroll position on file browsing

### ISSUE THREAD

**Issue by vromero** [mulesoft/api-designer#327]
It's bugging me a lot every time I go to an example, when I go back to the raml file I'm back on the line 0 rather than on the line I was when I browsed the example.

**Comment by sichvoge** [comment]
guess it has something to do with CodeMirror and the current implementation of using the same instance through multiple files. @blakeembrey  pushed a PR for this - that might help to get this done as well. Any comments from anyone?

**Comment by sichvoge** [comment]
This has been implemented. Closing it.
