### ISSUE TITLE
Response Body not rendering

### ISSUE THREAD

**Issue by joshrivers** [mulesoft/api-designer#329]
Using latest, when I post a API call, the response does not render in the body box until I resize the browser and get CodeMirror to reflow.

**Comment by sichvoge** [comment]
Hi @joshrivers, can you post more details about the environment you're running the API Designer on?

**Comment by joshrivers** [comment]
Tried with api-designer trunk and 0.0.3 from NPM
$ node -v
v0.12.5

Mac OS X 10.10.3
Chrome Version 43.0.2357.132 (64-bit)
Safari Version 8.0.6 (10600.6.3)
Firefox 38.0.5

**Comment by sichvoge** [comment]
Hi @joshrivers,

seems to me that this one is more related to the api-console. I'll create a separate issue there and close this one.
