### ISSUE TITLE
just tried with api-designer. hope it can has a auto save function

### ISSUE THREAD

**Issue by RyanZhu1024** [mulesoft/api-designer#330]
it'a great tool. but maybe it's because I use IDEA too much without worrying saving files. Every time I change the content and forget to save, and switch to another file and switch back, all the content just added had gone. Sometimes when I edit too much and then realise I have to do those again, really frustrating... Just hope it can have an auto save function.

**Comment by usarid** [comment]
Hmm, it *is* supposed to warn you if you try to switch to something else
and may lose your data. Is there a specific reproducible scenario? That
would be great -- we should do *everything possible* to avoid losing data.

**Comment by sichvoge** [comment]
I can't confirm the behaviour right now. :/ Having the reproducible scenario would be great

**Comment by RyanZhu1024** [comment]
@usarid @sichvoge it's odd... I can't reproduce it... I was using safari on Mac Yosemite yesterday, added some raml in a raml file and changed to a schema file in the same project. didn't close the web page. And then switched back to the previous raml file, and some content just typed was lost... But I did it again just now and all were there, nothing lost... have no idea... is there a way to start api-designer on a debug mode? maybe next time I can post some stack trace.

**Comment by sichvoge** [comment]
There is no debug mode for the api-designer per se, but you can use inspecting tools of your browser to debug through the application. If you use Chrome I can recommend the *AngularJS Batarang* extension. 

But you're right, it would be good to have some debug output to actually enable users to send us a complete stack trace. I'll close this issue as it is not relevant. If more than one can re-produce it, we can open it again ;)
