### ISSUE TITLE
RAML hints sometimes appear in non-RAML files

### ISSUE THREAD

**Issue by juancoen** [mulesoft/api-designer#342]
I don't have steps to reproduce this 100% of the times, but sometimes I get RAML hints (protocols:, documentation:, etc.) in non-RAML files.

I've been able to reproduce this in standalone mode and in embedded mode.

Steps that sometimes result in this are:
- Have two RAML files and on JSON file
- Select the JSON file
- Select the non-root RAML file and delete it
- The editor should open the JSON file
- Observe if hints are enabled

I'm adding a screenshot of how this looks:
![screen shot 2015-07-22 at 6 18 50 pm](https://cloud.githubusercontent.com/assets/1169708/8837728/33707040-309e-11e5-80cb-1942d8032186.png)

And an error that might be related to this:
![screen shot 2015-07-22 at 6 20 10 pm](https://cloud.githubusercontent.com/assets/1169708/8837748/5a20fd18-309e-11e5-8bb9-4b8b4644e67f.png)

Thanks!

**Comment by nmarinel01** [comment]
Cannot reproduce this behavior with latest Api Designer version. 
Please, verify and reopen if necessary
Thank you !
