### ISSUE TITLE
Check examples against schema

### ISSUE THREAD

**Issue by vromero** [mulesoft/api-designer#359]
This is just a wish, but if examples and schemas are given, examples should be tested against the given schemas for a less error prone apis.

**Comment by robertlevy** [comment]
+1.  We created a custom tool for this but it should ideally be part of raml-parser.

**Comment by sichvoge** [comment]
Indeed, we are currently working on couple of tooling where this kind of validation is a big part as well. News coming soon ;)

**Comment by sichvoge** [comment]
The new parser basically supports that already for .8 as warning and in 1.0 those are errors. We decided to have warnings in .8 RAML's for backwards compatibility. Unfortunately the designer does not show warnings yet. Its on our todo list.

You can track that [here](https://github.com/mulesoft/api-designer/issues/403).
