### ISSUE TITLE
Give support for RAML 1.0

### ISSUE THREAD

**Issue by rvegas** [mulesoft/api-designer#369]
Is there a milestone in the roadmap to support RAML 1.0?
Types and Examples are key improvements that would be very nice to have.

**Comment by dmartinezg** [comment]
Hi @rvegas, we are currently spiking to calculate the effort needed, but I can assure you, we will be updating both, designer and console.

thanks

**Comment by tvervest** [comment]
+1 looking forward to 1.0 support :+1:

**Comment by YvanDaSilva** [comment]
That would be really sweet.
Also to have a proper documentation & manualtesting generation like raml2html, sadly has no time to pursue his projects based on raml.

**Comment by h4t0n** [comment]
+1 :+1:

**Comment by sichvoge** [comment]
@YvanDaSilva Can you confirm, you want to have an option inside the designer to generate documentation such as raml2html?

**Comment by YvanDaSilva** [comment]
Well there is two ways to do this:
- use an external product like "raml2html" that does extrac documentation from a RAML
or
- directly be able to build & extract html documentation (preferably with testing integrated like the designer is able to do) from the designer.

**Comment by sichvoge** [comment]
We could integrate with the PHP project for raml2html - https://github.com/mikestowe/php-raml2html. That is still in maintenance.

**Comment by davidmoss** [comment]
+1  :+1:

**Comment by sichvoge** [comment]
I created a new issue for the documentation generation integration. https://github.com/mulesoft/api-designer/issues/372

**Comment by damirv** [comment]
Can you give an ball park estimate when 1.0 will be supported? Are there currently any other tools available that can generate docs for a 1.0 spec?

On a side note: I'm just starting out with RAML. After reading the 1.0 spec and playing with it in Atom, I noticed a few mistakes in the examples, probably outdated syntax; I will report these in another issue.

**Comment by sichvoge** [comment]
@damirv are those mistakes on the RAML.org website?

Regarding any estimated date for the support, you might have seen that RAML 1.0 is in (RC) stage and there will be some changes to the spec based on couple of feedback from the community. We are currently testing the parsers by integrating them into the api-console. We will have an MVP soon, but plan to have the full tested support by late 2016Q1.

Regarding other tools, its the same state I guess - most tooling vendors are testing the current parsers and give a lot feedback. These parsers are completely new and rewritten from scratch to support 0.8 and 1.0.

**Comment by nash-ye** [comment]
1+, I hope to see more support for RAML 1.0 very soon. :)

**Comment by stevenpollack** [comment]
+1 -- API Designer has one killer feature that Atom clearly does not: mocks. It'd be sweet if we could get RAML 1.0 support.

**Comment by sichvoge** [comment]
Its in development; the first part here is the API Console that is embedded here in the designer. You already find couple of commits around the RAML 1.0 support in the console branch.

**Comment by neilhosey** [comment]
Was this ever released?  Im really looking forward to a good RAML 1 editor.

I

**Comment by sichvoge** [comment]
It was indeed. The current master contains support for RAML 1.0 as well.

**Comment by beno** [comment]
Current master still reports 'Unsupported RAML version'.

I am a bit puzzled about the overall state of RAML 1.0 adoption. Lots of 'almost there' seemingly.

**Comment by sichvoge** [comment]
The spec has been closed 2 weeks ago. Obviously we need to give people the time in between needed to update their tools.

With regards to the master. I have it running fine locally.

![image](https://cloud.githubusercontent.com/assets/498114/15885726/ee3a5012-2d50-11e6-8f1d-10caccface12.png)

What did you execute to run it? Maybe I can help to get you started.

**Comment by beno** [comment]
Hi, I think I may have been looking at the previous stable version earlier, but when try to run the current master the browser loads the api-designer javascript files and then errors out with 

api-designer.js:9408 Uncaught ReferenceError: angular is not defined

**Comment by sichvoge** [comment]
Have you tried the following:

```
git clone https://github.com/mulesoft/api-designer.git
cd api-designer
npm install
bower install
grunt server
```

?

**Comment by beno** [comment]
Thanks for the help, we are getting closer, but still no cigar. I missed the bower and grunt steps, and I have done them now after a fresh reinstall. The application loads, but now gives me an 'undefined' error message, regardless of version specification.

<img width="407" alt="screen shot 2016-06-08 at 12 19 48" src="https://cloud.githubusercontent.com/assets/46243/15891214/d56b6eea-2d73-11e6-861c-ea10691cf84b.png">
<img width="399" alt="screen shot 2016-06-08 at 12 20 04" src="https://cloud.githubusercontent.com/assets/46243/15891215/d5963648-2d73-11e6-9b3f-fb5eb1277453.png">

**Comment by beno** [comment]
Succes! The error seemed to stem from unuploaded includes from the other RAML file. So I guess the issues here are

- the error 'bleeds' from one API spec to the next
- the error is not specific

But other than that, I can now work on 1.0! Yay! Thanks for your help.

**Comment by shadowhand** [comment]
There are still a number of errors present when pasting the example file from http://raml.org/developers/whats-new-raml-10 into API Designer.

**Comment by sichvoge** [comment]
Which one in particular?

**Comment by sichvoge** [comment]
@shadowhand its a mistake in how the example gets rendered on the webpage. I already raised an issue [here](https://github.com/raml-org/raml-website/issues/13).

**Comment by shadowhand** [comment]
@sichvoge thanks, that helps immensely!

**Comment by sichvoge** [comment]
No problem. Hope to get that fixed soon.

**Comment by sichvoge** [comment]
BTW, I am closing this issue as the current master supports 1.0. If there are any problems with that please file a new issue.
