### ISSUE TITLE
import files from a zip file not working correctly.

### ISSUE THREAD

**Issue by vganesh** [mulesoft/api-designer#370]
Steps to be followed to reproduce this issue. 

1. Start api-designer 
2. Get all the files from git clone https://github.com/raml-org/raml-tutorial-200.git 
3. Create a zip files that has all these files. 
4. Import it from the API designer. 
5. Error is: file with path "/jukebox-include-song.schema" does not exist. 
6. This file does exist. You can see it listed on the left pane. 
7. If you create a valid raml file which include other files, then export it and then import it from another browser
![apiimportbug](https://cloud.githubusercontent.com/assets/841192/11078512/4bc68426-87bb-11e5-8264-2dffca7933e3.png)
, the error is path "..." does not exist, when it does exist. 

Thx,

**Comment by dmartinezg** [comment]
This is a known behaviour, importing files does not save them automatically, and hence the parser does not *see* it.

I *personally* would like import to save all files.

:+1: if you would like that change.

**Comment by sichvoge** [comment]
+1

**Comment by vganesh** [comment]
Thanks. I can verify verify if I save files after import, then I can verify it works as expected and the error I had mentioned disappears.
