### ISSUE TITLE
No way to turn shelf back on in raml editor

### ISSUE THREAD

**Issue by michaelgriffithus** [mulesoft/api-designer#379]
I accidentally turned off the shelf by clicking on the shelf icon. Now it does not appear and no way to turn it back on.

**Comment by dmartinezg** [comment]
The shelf only shows up when you are in a RAML file (the extension is  `raml`).

If you are not in a RAML file you will not get the icon at all. If you are editing a .raml file, and the shelf does not show up, it may be a bug indeed.

**Comment by michaelgriffithus** [comment]
File is  extension is .raml See screenshot
https://www.dropbox.com/s/a6yk0mfiajgfhhv/Screenshot%202016-02-26%2013.37.27.png?dl=0

**Comment by dmartinezg** [comment]
On Anypoint Platform specifically there is an issue with 100% vertical space not taking into account the navigation bar, then there is a vertical scroll, which hides the bottom of the page. Perhaps in your case you cannot scroll vertically either (if I scroll down I can see the icon, when collapsed).

I will pass this along to that team of devs, but it probably is an issue on the Anypoint Platform, not the designer.

**Comment by michaelgriffithus** [comment]
exactly the problem, the scroll bar is neither visible or obvious. 

Thanks!

**Comment by dmartinezg** [comment]
Vertical scroll on that page has been a thorn on my side for too long. Thanks! I'll close this one.
