### ISSUE TITLE
Request entity too large - API designer issue

### ISSUE THREAD

**Issue by arubalac** [mulesoft/api-designer#380]
Hello,

I pasted a RAML  in a new RAML file inside the API designer but It was throwing erorr reporting that "**Request Entity too large**" . What I understand about the same from the mule forum is that after a certain range of sizer\length the designer is not able to hold the file.

The RAML which I am using is already a trimmed down version with all the necessary segregation done.
Could you please suggest any resolution or will this be fixed with any patch.?

PFA the RAML file for the reference.

Note: The RAML file attached is generated out of the swagger to raml convertor so that JSON schema files are generated right on the same RAML file instead of generating individual JSON schema file. 

Regards
Arun
[inventory.zip](https://github.com/mulesoft/api-designer/files/153709/inventory.zip)

**Comment by sichvoge** [comment]
Hi Arun, the API Designer is tight to the File browser cache and limited on that. Anyways, the file you attached works perfectly fine. I am closing this issue for now, please let us know if its still not working.
