### ISSUE TITLE
Missing `headers` in the palette

### ISSUE THREAD

**Issue by sichvoge** [mulesoft/api-designer#384]
![image](https://cloud.githubusercontent.com/assets/498114/13635920/b9a2297a-e5f6-11e5-91a5-2b46760f9bc5.png)

According to the 0.8 spec, one should be able to define `description`, `body`, and `headers` to a HTTP status node. I am able to define it and it passes validation, but as you can see in the image above, it's not part of the palette and it's also missing in the auto-completion.

**Comment by usarid** [comment]
headers (plural), not header






On Wed, Mar 9, 2016 at 5:00 AM -0800, "Christian Vogel" <notifications@github.com> wrote:
















According to the 0.8 spec, one should be able to define description, body, and header to a HTTP status node. I am able to define it and it passes validation, but as you can see in the image above, it's not part of the palette and it's not in the auto-completion.

**Comment by sichvoge** [comment]
Changed it!

**Comment by carowright** [comment]
Already fixed in develop branch. Will be released in next version.
