### ISSUE TITLE
api-designer can't import swagger zip file

### ISSUE THREAD

**Issue by edwardramsey** [mulesoft/api-designer#387]
I install api-designer with npm. Now I want to import a swagger.zip file. But when I click import button, no choose box to select my file.
![image](https://cloud.githubusercontent.com/assets/4987288/15008493/32141dbc-1213-11e6-91a4-4c1d109a7318.png)

my system is OSX 10.11.4
my chrome version is  50.0.2661.86 (64-bit) 
my api-designer version is 
![image](https://cloud.githubusercontent.com/assets/4987288/15008523/63e17b1e-1213-11e6-9f86-7a80f940c7bf.png)

**Comment by sichvoge** [comment]
Can you attach the zip file? Maybe there is something wrong and there is just an issue of giving you feedback on that.

**Comment by edwardramsey** [comment]
Actually I haven't choose my zip file. It's not because of the zip file. Viewing the web page I find the difference blow.  I hope it can help you.

<img width="938" alt="2016-05-04 17 42 08" src="https://cloud.githubusercontent.com/assets/4987288/15011052/4239be68-1222-11e6-8084-256746ffa14f.png">
<img width="972" alt="2016-05-04 17 42 22" src="https://cloud.githubusercontent.com/assets/4987288/15011152/d36974aa-1222-11e6-8134-9dd2299a2a1f.png">

**Comment by sichvoge** [comment]
I am using chrome as well and don't have problems! :(

**Comment by nmarinel01** [comment]
Cannot reproduce this behavior with latest Api Designer version.
Please, verify and reopen if necessary
Regards
