### ISSUE TITLE
The star against the saved item in API Designer never goes away even after save

### ISSUE THREAD

**Issue by rbkn** [mulesoft/api-designer#388]
When I save one of my files in RAML API designer, the star next to the filename indicating the file has changed disappears.  When moving away from this file to work on another, the star returns indicating a change although there has been no change.

This happens only with one specific file (contains traits).

**Comment by dmartinezg** [comment]
interesting, this is when API designer uses localStorage for saving files or on a custom FS implementation?

**Comment by rbkn** [comment]
not sure what it's using for storage (Firefox Browser) , but if it is local storage, it's just NTFS.

**Comment by nmarinel01** [comment]
Cannot reproduce this behavior with latest Api Designer version.
Please, verify and reopen if necessary
Regards
