### ISSUE TITLE
 api-designer doesn't run

### ISSUE THREAD

**Issue by fuguoSorp** [mulesoft/api-designer#389]
Hi there,

I'm trying to install and run api-designer on my windows 7 machine. I followed the instruction here (https://github.com/mulesoft/api-designer), but it doesn't run successfully (refer to the attached screenshot). 
![apidesignererror](https://cloud.githubusercontent.com/assets/19422244/15347786/048fec40-1d08-11e6-922e-8b89e205f5fa.jpg)

Could you please offer some advice? Thanks.

Kind regards,
Fuguo

**Comment by sichvoge** [comment]
I don't see any problems with the installation to be honest. Can you check your global NPM index if its there. Not sure where npm does store it on Windows :)

**Comment by sichvoge** [comment]
Maybe this helps http://stackoverflow.com/questions/9587665/nodejs-cannot-find-installed-module-on-windows

**Comment by nmarinel01** [comment]
I tried the  steps using Windows and I have no problem. Cannot reproduce the behavior you described. 
Please, verify again and reopen if necessary
Regards
