### ISSUE TITLE
Use of TypeA-or-TypeB types fails to parse

### ISSUE THREAD

**Issue by ekoutanov** [mulesoft/api-designer#391]
Version: branch features/raml-1.0 commit 5c80401 api-designer version 0.0.6
OS: El Capitan 10.11.4
Browser: Chrome 50.0.2661.102 (64-bit)

The following example fails:
```
#%RAML 1.0
title: Animals test

mediaType: application/json

types:
  CatOrDog:
    type: Cat | Dog # elements: Cat or Dog 
  Cat:
    type: object
    properties:
      name: string
      color: string
  Dog:
    type: object
    properties:
      name: string
      fangs: string
      
/animals/{animalId}:
  get:
    responses:
      200:
        body:
          type: CatOrDog
          example: |
            {
              "name": "Rex",
              "fangs": "big ones"
            }
```
^^^ **fails**
Two errors are produced on the example node:
- object is expected
- union type options does not pass validation

An awkward hack is to wrap the response in a property; then OR types will work.
```
#%RAML 1.0
title: Animals test

mediaType: application/json

types:
  CatOrDog:
    type: Cat | Dog # elements: Cat or Dog
  Cat:
    type: object
    properties:    
      name: string
      color: string
  Dog:
    type: object
    properties:
      name: string
      fangs: string
      
/animals/{animalId}:
  get:
    responses:
      200:
        body:
          type: 
            properties:
              wrapper: CatOrDog
          example: |
            {
              "wrapper": {
                "name": "Rex",
                "fangs": "big ones"
              }
            }
                
```
^^^ **works**
So evidently the bug only occurs when the AorB type is applied at the topmost level in the response object.

**Comment by sichvoge** [comment]
Hi, it seems that the parser tries to validate an object against your YAML type, but since you use `|` you basically define a string. I raised an issue inside the parser repo to fix that as that should not happen. You can track the progress [here](https://github.com/raml-org/raml-js-parser-2/issues/247).

For now, if you remove the pipe symbol after `example:` you should be good to go, but if its not too urgent I'd wait for the fix.

**Comment by ekoutanov** [comment]
Hi, thanks heaps for that! Unfortunately our real case (not the dog/cat example) which prompted this issue submission is a very large API with numerous examples and so we have extensively modularised it. All examples are in their own .json files and referred to from the main api.raml file using !include directives. It seems that !include behaves exactly the same way. Do you know of a workaround when externalised samples are used?

Another question I had was: How soon do fixes and enhancements to the api-designer and raml-js-parser make it to AnyPoint?

**Comment by sichvoge** [comment]
> How soon do fixes and enhancements to the api-designer and raml-js-parser make it to AnyPoint?

Usually it takes some time till that goes into the MuleSoft product. If that is not a critical hot fix, changes / enhancements need to wait till the next release window.
