### ISSUE TITLE
API designer continually give error for traits , traits should be in a map in RAML 1.0 when trait is defined as a map

### ISSUE THREAD

**Issue by Mikey887** [mulesoft/api-designer#398]

**Comment by sichvoge** [comment]
Can you please give more details. Whats your example? Usually this happens when you use something like:

```
#%RAML 1.0
title: Test

traits:
  - paging:
```

The `-` is not allowed in RAML 1.0.

**Comment by Mikey887** [comment]
so i have api.raml with 

`#%RAML 1.0
title: Raml customer context header
baseUri: https://api.dropbox.com/{version}
version: 0.1
traits:
   Context:
      usage: Apply this to any method that needs to be secured
      description: Some requests require authentication.
      headers:
        CustomerContext:
          properties:
            customerId:
              required: true
              example: '1234567890'
            customerType:
              required: true
            officialId:
securitySchemes:
  custom: !include securitySchema.raml


/addresses:
  get:
    is: [Context]
    
    
/phones:
  get:
    is: [Context]`

and securitySchema.raml with
`#%RAML 1.0 SecurityScheme
title:HMAC security schema
  custom_scheme:
    description: A custom security scheme for authenticating requests.
    type: x-HMAC
    describedBy:
      headers:
        X-Bar-HMAC-Signature:
          description: Used to send HMAC signature of the message body and headers
          type: string
          required: true
        X-Bar-HMAC-Metadata:
      responses:
        401:
          description: |
            Bad token.ppp
        403:`

and either get an error that custom must be a map or 
![2016-06-22](https://cloud.githubusercontent.com/assets/9251687/16276302/aede30e0-38a5-11e6-85fe-b4c059378337.png)

**Comment by sichvoge** [comment]
Yes the error is fully valid. A RAML fragment does not really have a title or a need to define a specific key. Its pure content. So if you change your `securitySchema.raml` to the following it should work:

```yaml
#%RAML 1.0 SecurityScheme

description: A custom security scheme for authenticating requests.
type: x-HMAC
describedBy:
  headers:
    X-Bar-HMAC-Signature:
      description: Used to send HMAC signature of the message body and headers
      type: string
      required: true
    X-Bar-HMAC-Metadata:
  responses:
    401:
      description: |
        Bad token.ppp
    403:
```

**Comment by Mikey887** [comment]
sweet , thanks
