### ISSUE TITLE
unknown type date-only

### ISSUE THREAD

**Issue by dbohl** [mulesoft/api-designer#399]
I created a queryParameter of type "date-only" (using RAML 1.0).  When I go to my mock service, it gives me an error - "unknown type date-only".

It seems to be the same issue as this:
https://github.com/mulesoft-labs/raml-dotnet-tools/issues/71
Although that one is under raml-dotnet-tools, so the change may not have made it to the online api designer yet?

**Comment by sichvoge** [comment]
Hi @dbohl, we have fixed that problem in our mocking service. Can you try again and let me know if that works again?

**Comment by dbohl** [comment]
It looks like it's working now.  Thanks!
