### ISSUE TITLE
Add the auto-completion module from the API Workbench

### ISSUE THREAD

**Issue by sichvoge** [mulesoft/api-designer#409]
The API Workbench has been a success for a lot of people already since it provides some very nice features. In the future we want to bring those into the web as well by separating modules out of the workbench and integrating them into the designer. As the team around the workbench started with that already, we will integrate the [raml-suggestions](https://github.com/mulesoft/raml-suggestions) module and replace the old legacy implementation.

**Comment by nmarinel01** [comment]
Related pull request [https://github.com/mulesoft/raml-suggestions/pull/8](url)
