### ISSUE TITLE
Import Swagger 2.0

### ISSUE THREAD

**Issue by sichvoge** [mulesoft/api-designer#411]
Some of you might come from a different angle and used a different spec language like Swagger before. Currently, we only have import for Swagger 1.2 > RAML 0.8 but thats not enough.

Since the release of RAML 1.0, and that being the default spec version; and also Swagger moving releasing 2.0 and OAI; we need to update the current import to Swagger 2.0 > RAML 1.0. We will modify and contribute, and integrate stoplights [api-spec-converter](https://github.com/stoplightio/api-spec-converter) for this purpose.

**Comment by glodieu** [comment]
Hi @sichvoge, I found that swagger 2.0 spec (https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md) has a field summary for methods and Raml 1.0 doesn't any equivalent. What do we need to do in this case? Thanks.

**Comment by sichvoge** [comment]
That is a very good questions. Let me think about that a little bit more and I'll let you know. Maybe someone else here in the community also wants to jump in and have some suggestions. Annotations maybe one way.
