### ISSUE TITLE
Support of the "nil" Type

### ISSUE THREAD

**Issue by Eliaenor** [mulesoft/api-designer#412]
Hi !

Since the new "nil" type is now in the official documentation for raml 1.0, is there any plan to add it to the Api-designer ?

Link to the doc for reference : [Here](https://github.com/raml-org/raml-spec/blob/master/versions/raml-10/raml-10.md#nil-type)

Vins.

**Comment by sichvoge** [comment]
Should be available very soon. We need to do some testing with the new parser first.

**Comment by vcourtin** [comment]
Nice ! Thanks for the answer and, of course, all the good work !

**Comment by nmarinel01** [comment]
Hi ! Nil support is included at last API Designer version
Regards
