### ISSUE TITLE
API Designer seems to not expand completely and send that information to the API Console

### ISSUE THREAD

**Issue by sichvoge** [mulesoft/api-designer#413]
Related to https://github.com/mulesoft/api-console/issues/320

Having the RAML document below, it seems that the API Designer does not fully expand the document so that the includes are resolved as well. The console therefore does not have all information to successfully render the necessary examples.

```yaml
#%RAML 1.0
title: My API

/repository:
  /projects:
    post:
      responses:
        400:
          description: User error
          body:
            application/json:
              examples:
                badKey: !include BadKey.json
                username: !include UsernameFail.json
                projectKey: !include ProjectKeyFail.json
```

![image](https://cloud.githubusercontent.com/assets/498114/17966886/fcd569a6-6abb-11e6-9cf2-a73c53a10762.png)

**Comment by nmarinel01** [comment]
Verified at QA environment. This fix will be included in next release.
