### ISSUE TITLE
Extending remote files now cannot resolve includes files/libs from the remote location

### ISSUE THREAD

**Issue by Gregroam** [mulesoft/api-designer#415]
Previously when extending from a remote location, the parser would try to obtain any remote files included from the local destination. 
[https://github.com/mulesoft/api-designer/issues/401](Issue)

Now it seems to be trying to resolve the files from the remote location, but it seems to have bodged the path to the the libraries from the remote api. 

For example my remote api uses a library file

remote api.raml

```
uses:
    SomeLib: ./lib/somelib.raml
```

and I am hosting it via the mulesoft portal stuff,

however on my other api (hosted on mulesoft)

api.raml

```
#%RAML 1.0 Extension
extends: https://anypoint.mulesoft.com/apiplatform/repository/v2/organizations/#####/public/apis/#####/versions/#####/files/root
```

I have scrubbed the url obviously, I get the error:
`ramlParser: loadPath: loadApi: content: /https:/anypoint.mulesoft.com/apiplatform/repository/v2/organizations/#####/public/apis/#####/versions/#####/files/lib/somelib.raml: no such path`

which seems like it's malformed the url, because of the `/https:/` part of it, however I can confirm that if I correctly enter the url into the browser myself it is able to fetch the library file.

Edit: I have just found this bug only occurs when using relative paths in the remote api.

**Comment by sichvoge** [comment]
This probably is a problem inside the parser. Can you please create an issue on js parser repo.

**Comment by nmarinel01** [comment]
Hi @Gregroam !
I have tested the parser fix with the following example. I think it covers your use case and works ok after Js Parser fix.
[remoteApiExample.raml.zip](https://github.com/mulesoft/api-designer/files/701727/remoteApiExample.raml.zip)

Please, let me know if you think the problem has been resolved.
Thanks and regards

**Comment by sichvoge** [comment]
Lets close this issue and its my personal pleasure, if we need to open it again, to open it again ;)
