### ISSUE TITLE
Api designer does not show feedback on errors

### ISSUE THREAD

**Issue by nmarinel01** [mulesoft/api-designer#422]
Steps to reproduce:
- pull of develop branch
- start api-designer
- import a swagger file syntactically correct.

Swagger file is imported to RAML 1.0 file, but no resources documentation is displayed at Resources panel. This is because there are errors that are not being displayed and cause resources documentation not to be generated

**Comment by sichvoge** [comment]
That is working but not in typed fragments. See #430
