### ISSUE TITLE
Api Designer : default RAML version to 1.0 when creating new files

### ISSUE THREAD

**Issue by nmarinel01** [mulesoft/api-designer#423]
Api Designer should default to #%RAML 1.0 when the following scenarios:
- creating a new raml file from scratch
- when importing Swagger 2.0 files
- when a new instance of API Designer starts

**Comment by sichvoge** [comment]
Why not? i would support that the API Designer creates RAML 1.0 files by default. If that is implemented already, lets make sure its across the board. For example when you start a new instance of the API Designer, the first file should also be a RAML 1.0 document
