### ISSUE TITLE
Moking service option is not visible

### ISSUE THREAD

**Issue by AyaanSaini** [mulesoft/api-designer#443]
I am new on this platform please suggest me how to on moking services option. I have attached a  gif.
![moking service issue](https://cloud.githubusercontent.com/assets/8656294/19426628/af7b4cb0-945b-11e6-93b2-19e6cece968c.gif)

**Comment by sichvoge** [comment]
This is MuleSoft's Anypoint Platform. It seems that the designer isn't fully displayed in the API Manager. Hence you don't see everything which is on the right side. Nothing to do with the designer itself. I would contact someone from the MuleSoft support team.
