### ISSUE TITLE
Mocking service activation fails to comment the real baseURI sometimes

### ISSUE THREAD

**Issue by llattes** [mulesoft/api-designer#462]
I cannot reproduce consistently and I cannot provide exact reproducing steps but sometimes the baseURI does not get properly commented out when activating the MS, causing an error due to duplicated baseURI.

<img width="699" alt="screen shot 2016-11-19 at 5 01 09 pm" src="https://cloud.githubusercontent.com/assets/2574415/20458139/c241379a-ae7a-11e6-996b-a50264cbc48f.png">

**Comment by sichvoge** [comment]
Yes, I have seen that same behaviour before. Again, couldn't really reproduce it as you said.

**Comment by nmarinel01** [comment]
I cannot reproduce it :(

**Comment by carowright** [comment]
Closing this as cannot reproduce.
