### ISSUE TITLE
Multiple examples in query parameter ignored

### ISSUE THREAD

**Issue by KevinMitchell** [mulesoft/api-designer#467]
Suppose I have

    queryParameters:
      sortOrder:
        example:
          Wibble

I correctly see the example in the formatted view.  However, if I try

    queryParameters:
      sortOrder:
        examples:
          ex1:
            description: ...
            value:
              Wobble
          ex2:
            description: ...
            value:
              Wabble

I get no examples displayed.

**Comment by nmarinel01** [comment]
Reproducible, thanks for reporting.

**Comment by carowright** [comment]
Hi @KevinMitchell!
This fix is available in version 0.4.9.
