### ISSUE TITLE
Mocking service fails with boolean values

### ISSUE THREAD

**Issue by russi7** [mulesoft/api-designer#470]
With the RAML below, the boolean value fails when is true, with false works correctly.

`  AdditionalBenefits:
    properties:
      cashSelected: boolean
[...]`

It works:
`{ [...] 
"cashSelected": false,
[...] }`

It fails with the below error:
`{ [...]
"cashSelected": true,
[...] }`
`{
  "error": "body: firstLife: cashSelected: not a boolean"
}`

**Comment by sichvoge** [comment]
Thanks @russi7, we will have a look at this.

**Comment by carowright** [comment]
Hi @russi7!
Thanks for reporting. I am closing this as the fix is currently available.
