### ISSUE TITLE
Mule Anypoint API Designer IE error

### ISSUE THREAD

**Issue by tovenkatr** [mulesoft/api-designer#475]
Anypoint API Designer shows error 'Promise is undefined' for below code. 
#%RAML 0.8
title: American Flights API
version: 1.0

**Comment by sichvoge** [comment]
Is this only happening within IE?

**Comment by tovenkatr** [comment]
Yes. Only in IE. Version 11.0.

**Comment by sichvoge** [comment]
If you are a MuleSoft customer, can I ask you to raise a support ticket? Let me know if that's not the case.

**Comment by gcallaway** [comment]
I have this same issue.  I am using the trial at this time as we are evaluating the solution.

Thanks!
