### ISSUE TITLE
How can I create a key named value? 

### ISSUE THREAD

**Issue by partounian** [mulesoft/api-designer#477]
I have a json response that looks like
```json
{
    name: "ui.fgcolor",
    value: "#FFFFFF",
    createdTime: "2016-10-19T02:20:33.601Z"
}
```
but with the key named value, I can only see "#FFFFFF" with the color blue in the preview of api designer?

EDIT:
However, the below json works fine.
```json
{
  "items": [
    {
      "name": "ui.fgcolor",
      "value": "#FFFFFF",
      "createdTime": "2016-10-19T02:20:33.601Z"
    }
  ]
}
```

**Comment by sichvoge** [comment]
You forgot double quotes which are important in JSON:

```json
{
  "name": "ui.fgcolor",
  "value": "#FFFFFF",
  "createdTime": "2016-10-19T02:20:33.601Z"
}
```

**Comment by partounian** [comment]
@sichvoge I apologise I forgot to mention that I already tried that.

**Comment by sichvoge** [comment]
It's working for me and everything is rendering just fine. So can you explain a little bit more what you are seeing? Maybe add an image to clarify things more for us.

**Comment by partounian** [comment]
I went and double checked adding double quotes to no avail.
Here is what I see in api-designer and api-console.
![image](https://cloud.githubusercontent.com/assets/2541595/25669292/ee502ef6-2fdd-11e7-9bf1-ed4a7f051a24.png)

**Comment by sichvoge** [comment]
what version do you use, thats what i see using 0.4.1

![image](https://cloud.githubusercontent.com/assets/498114/25673069/0a581690-302e-11e7-8d11-095dee2071a8.png)

**Comment by partounian** [comment]
Okay so adding the double quotes and the `|` fixes it.
