### ISSUE TITLE
Syntax error in RAML 200 tutorial

### ISSUE THREAD

**Issue by harvey911** [mulesoft/api-designer#492]
In "RESOURCES TYPE" ->
  responses:
      200:
        body:
          application/json:
            example: |
              "songs": [
                  {
                    "songId": "550e8400-e29b-41d4-a716-446655440000",
                    "songTitle": "Get Lucky"
                  },
                  {
                    "songId": "550e8400-e29b-41d4-a716-446655440111",
                    "songTitle": "Loose yourself to dance"
                  },
                  {
                    "songId": "550e8400-e29b-41d4-a716-446655440222",
                    "songTitle": "Gio sorgio by Moroder"
                  }
                  ]

It is not correct, the onling API editor will point out "WARNING". 

THe correct one is like this:
  example: |
            {  "songs": [
                  {
                    "songId": "550e8400-e29b-41d4-a716-446655440000",
                    "songTitle": "Get Lucky"
                  },
                  {
                    "songId": "550e8400-e29b-41d4-a716-446655440111",
                    "songTitle": "Loose yourself to dance"
                  },
                  {
                    "songId": "550e8400-e29b-41d4-a716-446655440222",
                    "songTitle": "Gio sorgio by Moroder"
                  }
                  ]
            }

**Comment by carowright** [comment]
Hi @harvey911!
Thank you for reporting. This is already fixed in [resource types section](https://raml.org/developers/raml-200-tutorial#resource-types)
