### ISSUE TITLE
!include no longer works as array item

### ISSUE THREAD

**Issue by Gregroam** [mulesoft/api-designer#493]
Main api.raml file

```
#%RAML 1.0

title: Test
version: 1

/foo:
  get:
    description: Test
    responses:
      200:
        body:
          application/json:
            example: {
              "data": [
                !include ./data.yml
              ]
            }
```

and the data.yml file
```
{
  "a": 1,
  "b": 2,
  "c": 3
}
```

Before including something as an array item used to work. Now it gives an error at the top of the file in the editor `Cannot read property 'canInclude' of undefined`. This has broken many of our projects as we use this heavily. Even using the yml way, instead of json way does not work either

```
example:
  data:
    - !include ./data.yml
```

The included file has to be yml, as we will nest further includes in the included files. However, in this test, even if I rename data.yml to data.json and change the include reference, the printed output on the side becomes

```
{
  "data": [
    null
  ]
}
```

**Comment by sichvoge** [comment]
Seems like a regression on the parser at the first look. Apologies for any inconvenience. We will look at this as soon as possible.

**Comment by Gregroam** [comment]
Thanks. Is there an ETA on when this will go live on the api designer?

**Comment by sichvoge** [comment]
Are you using the reference implementation here on Github or MuleSoft's Anypoint platform?

**Comment by agustinlg** [comment]
Hey @Gregroam ETA is July 15. Thanks.

**Comment by Gregroam** [comment]
@sichvoge Mulesoft's Anypoint platform. @agustinlg thanks

**Comment by carowright** [comment]
Hi @Gregroam!
The fix is already in Mulesoft's Anypoint platform.
