### ISSUE TITLE
API Manager in Anypoint RAML error

### ISSUE THREAD

**Issue by Loupie** [mulesoft/api-designer#495]
When I create a new API it prefills the RAML with this
#%RAML 1.0
title: american.raml
version: 1.0
---> It starts with a red X next to the 1st line and when I hover over it it says "Promise" is undefined.

But it already has an error that does not go away when I continue building the RAML.

**Comment by sichvoge** [comment]
Hi, thanks for raising. We look into that as soon as possible.

**Comment by PaulWBarber** [comment]
Any updates on this?  I get same issue.  Version 0.3.2.

**Comment by carowright** [comment]
Hi @PaulWBarber!
This is fixed in version 0.4.9.

**Comment by carowright** [comment]
Hi @Loupie!
I am closing this issue as this is now fixed in API Manager. Feel free to reopen if applies.
