### ISSUE TITLE
traits tag should be clickable

### ISSUE THREAD

**Issue by cspiegl** [mulesoft/api-designer#93]
This tags would be great if clickable and a dropdown should be shown with the information the trait is about.

![screenshot](https://f.cloud.github.com/assets/1096384/1492118/f37b30d2-47bb-11e3-91a9-a3c630fd1388.png)

**Comment by sichvoge** [comment]
This is definitely a great enhancement for the API Console. That said, I will close it in here and re raise it on the console related github repo. I'll post the link in here.

**Comment by sichvoge** [comment]
see new issue on the api-console github repo https://github.com/mulesoft/api-console/issues/141
