### ISSUE TITLE
Question - And a really dumb one...

### ISSUE THREAD

**Issue by JemDay** [mulesoft/api-designer#95]
Firstly, thanks for contributing this, i'm slowly coming up-to-speed with RAML and this is a good way to get there.

Now my dumb question, and i'm really embarrassed to ask this !.

I'm running a local instance of the tool that i cloned from GIT, it runs fine but for the life of me i can't find where the raml files are being written,; as i suspect i'll be writing markdown and json schema files as well i need the ability to author such items in other tools and master the coherent set of artifacts under SCM.

And in the interest of clarity i'm in no way a JS or Node expert ;-)

Thanks again

Jem...

**Comment by sichvoge** [comment]
Anyone else has some opinion on that. What about letting people decide where they want to store there files. We could implement some hooks to enable people develop their own "repository" and add that to our API Designer. Then you can configure the API Designer to use a specific "repository". There are many implementation out there which we can merge to that like @brianmc or the local filesystem one I have also seen somewhere on github. 

My guess is this would also solve the version control issue as if you use a filesystem repository "plugin/adapter/hook", you can just reuse the tools you already have for git or svn or whatever. It doesn't need to be integrated into the designer. I think that is a lot of overhead and therefore not necessary.

What are your thoughts? @alejandroschenzle @usarid @dmartinezg 

It should be the browser cache for the MuleSoft hosted version by default, btw.

**Comment by sichvoge** [comment]
related to https://github.com/mulesoft/api-designer/issues/199
